### ISSUE TITLE
Runtime Manager

### ISSUE THREAD

**Issue by karamolegkos** [DIASTEMA-UPRC/runtime-manager#1]
# TODO

- [x] Build Runtime Manager
- [x] Build Diastema API
- [x] Build Runtime Manager K8s Component
- [ ] Make Documentation for this component.

**Comment by karamolegkos** [comment]
Everything is getting through a testing phase currently.
The k8s Component needs a tiny bit of code. Then the testing phase will continue.

**Comment by karamolegkos** [comment]
TODO: add more debugging printings.

**Comment by karamolegkos** [comment]
# TODO

Almost done. 

- [x] Waiting for some specifications by @konvoulgaris (chack slack).

**Comment by karamolegkos** [comment]
Moved to Integration as it is ready for deployment.

**Comment by karamolegkos** [comment]
# Bug Found

Το κατά το σήκωμα ενός spark job το command που το σηκώνει "κολάει" στον κώδικα. 
Πρέπει ο κώδικας να συνεχίζει χωρίς να περιμένει το σχετικό output.

**Comment by karamolegkos** [comment]
Γίνεται integrated μετά από update.

**Comment by karamolegkos** [comment]
# New Bug

Υπάρχει ένα missconfiguration στο σήκωμα του μοντέλου μέσω Spark. Γίνεται σχετική συζήτηση μεταξύ μου και του @konvoulgaris για την επίλυση του προβλήματος.

**Comment by karamolegkos** [comment]
Integrated.
--> Tested and working as expected.
